import time
import os
from termcolor import colored
import requests as req

def charg(chrag1=0.1,t=colored("Démarrage du système...","blue",attrs=["bold"])):
    os.system("clear")
    print(t)
    print(colored("[#####-----------------------------------------------------------------------------------------------] 5%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[##########------------------------------------------------------------------------------------------] 10%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[###############-------------------------------------------------------------------------------------] 15%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[####################--------------------------------------------------------------------------------] 20%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[#########################---------------------------------------------------------------------------] 25%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[##############################----------------------------------------------------------------------] 30%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[###################################-----------------------------------------------------------------] 35%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[########################################------------------------------------------------------------] 40%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[#############################################-------------------------------------------------------] 45%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[##################################################--------------------------------------------------] 50%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[#######################################################---------------------------------------------] 55%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[############################################################----------------------------------------] 60%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[#################################################################-----------------------------------] 65%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[######################################################################------------------------------] 70%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[###########################################################################-------------------------] 75%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[################################################################################--------------------] 80%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[#####################################################################################---------------] 85%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[##########################################################################################----------] 90%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[###############################################################################################-----] 95%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")
    print(t)
    print(colored("[####################################################################################################] 100%","blue",attrs=["bold"]))
    time.sleep(chrag1)
    os.system("clear")